version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5005:5000
    env_file:
      - ./.env-dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_flask
      - POSTGRES_PASSWORD=dev_flask
      - POSTGRES_DB=dev_flask_db

volumes:
  postgres_data: